#!/usr/bin/env python
#coding:utf-8

import os, sys
import getpass
import platform
#import __init__
from record import record_videos

sysstr=platform.system().strip()
if sysstr == 'Windows':
    pass
elif sysstr == 'Linux':
    # set tab
    if os.path.isfile(os.path.expanduser('~/.ssh/known_hosts')):
        cmd = '''complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\["`;)" %s''' % sys.argv[0]
        os.system(cmd)
else:
    print "Only support windows or linux,exit."
    sys.exit()


def usage():
    print '''\033[;32m  connection remote hostname operator and record all infomation.

    Usage:  %s hostname or ip (default username current username,port 22)
            %s user@ip (default port 22)
            %s user@ip:port
    \033[0m''' % (sys.argv[0],sys.argv[0],sys.argv[0])
    sys.exit()

@record_videos
def run(username, hostname, port):
    print hostname, 'closed.'

# currently username
username = getpass.getuser()
if len(sys.argv) > 1:
    hostname = sys.argv[1]
    if hostname.find('@') >= 0:
        username, hostname = hostname.split('@')
else:
    usage()
    sys.exit(1)
port = 22
if hostname.find(':') >= 0:
    hostname, portstr = hostname.split(':')
    port = int(portstr)

run(username, hostname, port)    



